/**
 * Resolves Google Fonts CSS URLs and writes the server render manifest.
 *
 * Usage: pnpm sync-template-fonts
 *
 * Does not write .woff2 files into the repo. The generated manifest stores
 * stable https://fonts.gstatic.com URLs; the render action downloads them to
 * os.tmpdir() on first use (see register_scene_fonts.ts).
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  buildGoogleFontsStylesheetUrlForFamilies,
  GOOGLE_FONT_CATALOG,
  SERVER_ONLY_FONT_FAMILIES,
} from "../lib/template-scene/google-fonts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const MANIFEST_PATH = path.join(
  ROOT,
  "lib/template-scene/server-font-manifest.generated.ts",
);

const CSS_USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

function extractWoff2Urls(css: string): string[] {
  const urls = new Set<string>();
  const pattern = /url\((https:[^)]+\.woff2)\)/g;
  for (const match of css.matchAll(pattern)) {
    urls.add(match[1]!);
  }
  return [...urls];
}

async function resolveFontFamilyUrls(family: string): Promise<string[]> {
  const cssUrl = buildGoogleFontsStylesheetUrlForFamilies([family]);
  if (!cssUrl) {
    return [];
  }

  const cssResponse = await fetch(cssUrl, {
    headers: { "User-Agent": CSS_USER_AGENT },
  });
  if (!cssResponse.ok) {
    throw new Error(`Failed to fetch CSS for ${family}: ${cssResponse.status}`);
  }

  const css = await cssResponse.text();
  const urls = extractWoff2Urls(css);
  if (urls.length === 0) {
    throw new Error(`No woff2 URLs found for ${family}`);
  }

  return urls;
}

async function main() {
  const manifest: Record<string, string[]> = {};
  const familiesToSync = [
    ...GOOGLE_FONT_CATALOG.map(({ family }) => family),
    ...SERVER_ONLY_FONT_FAMILIES,
  ];

  for (const family of familiesToSync) {
    process.stdout.write(`Syncing ${family}… `);
    try {
      const urls = await resolveFontFamilyUrls(family);
      manifest[family] = urls;
      process.stdout.write(`ok (${urls.length} urls)\n`);
    } catch (error) {
      process.stdout.write("failed\n");
      console.error(error);
      process.exitCode = 1;
      return;
    }
  }

  const contents = `/** Generated by scripts/sync-template-fonts.ts — do not edit manually. */
export const TEMPLATE_FONT_MANIFEST: Record<string, readonly string[]> = ${JSON.stringify(manifest, null, 2)};
`;
  await writeFile(MANIFEST_PATH, contents, "utf8");
  console.log(`Wrote manifest with ${Object.keys(manifest).length} families.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
