/**
 * Downloads catalog Google Fonts and generates a URL manifest for server render.
 *
 * Usage: pnpm sync-template-fonts
 *
 * Convex Node actions cannot read bundled .woff2 files from the repo at runtime,
 * so the manifest stores stable https://fonts.gstatic.com URLs. The render action
 * downloads them to os.tmpdir() on first use and registers via FontLibrary.use().
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  buildGoogleFontsStylesheetUrlForFamilies,
  GOOGLE_FONT_CATALOG,
  SERVER_ONLY_FONT_FAMILIES,
} from "../lib/template-scene/google-fonts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const FONTS_DIR = path.join(ROOT, "convex/automations/render/fonts");
const MANIFEST_PATH = path.join(
  ROOT,
  "lib/template-scene/server-font-manifest.generated.ts",
);

const CSS_USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

function slugifyFamily(family: string): string {
  return family.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

function extractWoff2Urls(css: string): string[] {
  const urls = new Set<string>();
  const pattern = /url\((https:[^)]+\.woff2)\)/g;
  for (const match of css.matchAll(pattern)) {
    urls.add(match[1]!);
  }
  return [...urls];
}

async function resolveFontFamilyUrls(family: string): Promise<string[]> {
  const cssUrl = buildGoogleFontsStylesheetUrlForFamilies([family]);
  if (!cssUrl) {
    return [];
  }

  const cssResponse = await fetch(cssUrl, {
    headers: { "User-Agent": CSS_USER_AGENT },
  });
  if (!cssResponse.ok) {
    throw new Error(`Failed to fetch CSS for ${family}: ${cssResponse.status}`);
  }

  const css = await cssResponse.text();
  const urls = extractWoff2Urls(css);
  if (urls.length === 0) {
    throw new Error(`No woff2 URLs found for ${family}`);
  }

  return urls;
}

async function cacheFontFamilyLocally(
  family: string,
  urls: string[],
): Promise<void> {
  const familyDir = path.join(FONTS_DIR, slugifyFamily(family));
  await mkdir(familyDir, { recursive: true });

  for (let index = 0; index < urls.length; index += 1) {
    const url = urls[index]!;
    const filePath = path.join(familyDir, `${String(index).padStart(2, "0")}.woff2`);
    const fontResponse = await fetch(url);
    if (!fontResponse.ok) {
      throw new Error(`Failed to download ${url}: ${fontResponse.status}`);
    }
    await writeFile(filePath, Buffer.from(await fontResponse.arrayBuffer()));
  }
}

async function main() {
  const manifest: Record<string, string[]> = {};
  const familiesToSync = [
    ...GOOGLE_FONT_CATALOG.map(({ family }) => family),
    ...SERVER_ONLY_FONT_FAMILIES,
  ];

  for (const family of familiesToSync) {
    process.stdout.write(`Syncing ${family}… `);
    try {
      const urls = await resolveFontFamilyUrls(family);
      manifest[family] = urls;
      await cacheFontFamilyLocally(family, urls);
      process.stdout.write(`ok (${urls.length} urls)\n`);
    } catch (error) {
      process.stdout.write("failed\n");
      console.error(error);
      process.exitCode = 1;
      return;
    }
  }

  const contents = `/** Generated by scripts/sync-template-fonts.ts — do not edit manually. */
export const TEMPLATE_FONT_MANIFEST: Record<string, readonly string[]> = ${JSON.stringify(manifest, null, 2)};
`;
  await writeFile(MANIFEST_PATH, contents, "utf8");
  console.log(`Wrote manifest with ${Object.keys(manifest).length} families.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
